[package]
name = "dextromethorphan-dst-decoder"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
name = "dextromethorphan_dst"
crate-type = ["cdylib"]

[dependencies]
dst-decoder = "=0.1.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "unwind"
strip = "symbols"
