<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Dextromethorphan.Core/Dextromethorphan.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="BunLabs.NAudio.Flac" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="NAudio.Vorbis" />
    <PackageReference Include="Concentus.Oggfile" />
    <PackageReference Include="TagLibSharp" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Audio/Probes/*">
      <LogicalName>Dextromethorphan.Infrastructure.Audio.Probes.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
