<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Dextromethorphan.Core/Dextromethorphan.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="BunLabs.NAudio.Flac" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="NAudio.Vorbis" />
    <PackageReference Include="TagLibSharp" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>
</Project>
